#ifndef CONNECTOR_VALUE_H
#define CONNECTOR_VALUE_H

static NAME2VALUE connector_type_valuelist[] = 
{
	{"INVALID",CONN_INVALID},
	{"P2P_BIND",CONN_P2P_BIND},
	{"P2P_RAND",CONN_P2P_RAND},
	{"CLIENT",CONN_CLIENT},
	{"CHANNEL",CONN_CHANNEL},
	{"SERVER",CONN_SERVER},
	{NULL,0}
};
static NAME2VALUE connector_state_valuelist[] = 
{
	// server's state
	{"CONN_SERVER_INIT",CONN_SERVER_INIT},
	{"CONN_SERVER_READY",CONN_SERVER_READY},
	{"CONN_SERVER_LISTEN",CONN_SERVER_LISTEN},
	{"CONN_SERVER_SERVICE",CONN_SERVER_SERVICE},
	{"CONN_SERVER_SLEEP",CONN_SERVER_SLEEP},
	{"CONN_SERVER_SHUTDOWN",CONN_SERVER_SHUTDOWN},
	// client's state
	{"CONN_CLIENT_INIT",CONN_CLIENT_INIT},
	{"CONN_CLIENT_CONNECT",CONN_CLIENT_CONNECT},
	{"CONN_CLIENT_RESPONSE",CONN_CLIENT_RESPONSE},
	{"CONN_CLIENT_DISCONNECT",CONN_CLIENT_DISCONNECT},
	// channel's state
	{"CONN_CHANNEL_INIT",CONN_CHANNEL_INIT},
	{"CONN_CHANNEL_ACCEPT",CONN_CHANNEL_ACCEPT},
	{"CONN_CHANNEL_HANDSHAKE",CONN_CHANNEL_HANDSHAKE},
	{"CONN_CHANNEL_CLOSE",CONN_CHANNEL_CLOSE},
	{NULL,0}
};
#endif
